const morgan = require('morgan');
const express = require('express');
const userRouter = require('./routes/userRoutes');
const tourRouter = require('./routes/tourRoutes');
const app = express();
app.use(express.json());
if (process.env.NODE_ENV === 'development') app.use(morgan('dev'));
console.log('port', process.env.NODE_ENV);
app.use(express.static(`${__dirname}/public`));
app.use('/api/v1/tours', tourRouter);
app.use('/api/v1/users', userRouter);
module.exports = app;
